# This is a basic workflow to help you get started with Actions

name: CI_TESTBRANCH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'
      - '!master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Verify if a build is needed
  check:
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - id: get_changed_files
        uses: masesgroup/retrieve-changed-files@v3
        with:
          format: 'csv'

      - id: check_files
        run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.get_changed_files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
              if [[ $added_modified_file == ".github/workflows/testbranch.yaml"* ]]; then
                echo "$added_modified_file is under the directory '.github/workflows'."
                echo "run_job=true" >> $GITHUB_OUTPUT
                break
              fi
              if [[ $added_modified_file == "src/jvm/src/JCOReflector/"* ]]; then
                echo "$added_modified_file is under the directory 'src/jvm/src/JCOReflector'."
                echo "run_job=true" >> $GITHUB_OUTPUT
                break
              fi
              if [[ $added_modified_file == "src/"* ]]; then
                echo "$added_modified_file is under the directory 'src/'."
                echo "run_job=true" >> $GITHUB_OUTPUT
                break
              fi
              if [[ $added_modified_file == "tests/jvm/"* ]]; then
                echo "$added_modified_file is under the directory 'tests/jvm/'."
                echo "run_job=true" >> $GITHUB_OUTPUT
                break
              fi
          done

  # This workflow contains a single job called "build"
  build_and_verify_nuget:
    needs: check
    if: needs.check.outputs.run_job == 'true'
    # The type of runner that the job will run on
    runs-on: windows-2022
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      # Support longpaths
      - name: Support long paths
        run: git config --system core.longpaths true
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          fetch-depth: '1'

      # Runs a set of commands using the runners shell
      - name: Build JCOReflectorCLI
        run: dotnet build --no-incremental --configuration Release /p:Platform="Any CPU" src\net\JCOReflectorCLI.sln

      - uses: nuget/setup-nuget@v1.2.0
        with:
          nuget-version: '5.x'
          
      - run: nuget pack src\net\CLI\JCOReflectorCLI.nuspec -OutputDirectory .\bin

      - uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: .\bin\*nupkg
          retention-days: 1

  # This workflow contains a single job called "build"
  build_testbranch:
    needs: check
    if: needs.check.outputs.run_job == 'true'
    # The type of runner that the job will run on
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        framework: [ 'net462', 'net6.0', 'net7.0', 'net8.0' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      # Support longpaths
      - name: Support long paths
        run: git config --system core.longpaths true
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          fetch-depth: '1'

      # Runs a set of commands using the runners shell
      - name: Build JCOReflectorCLI
        run: dotnet build --no-incremental --framework ${{ matrix.framework }} --configuration Release /p:Platform="Any CPU" src\net\JCOReflectorCLI.sln

      # Runs a set of commands using the runners shell
      - name: Copy configuration file
        if: matrix.framework == 'net6.0'
        run: Copy-Item .github\workflows\JCOReflectorCLI6.0.runtimeconfig.json -Destination bin\net6.0\MASES.JCOReflectorCLI.runtimeconfig.json -Force
      
      # Runs a set of commands using the runners shell
      - name: Copy configuration file
        if: matrix.framework == 'net7.0'
        run: Copy-Item .github\workflows\JCOReflectorCLI7.0.runtimeconfig.json -Destination bin\net7.0\MASES.JCOReflectorCLI.runtimeconfig.json -Force
          
      # Runs a set of commands using the runners shell
      - name: Copy configuration file
        if: matrix.framework == 'net8.0'
        run: Copy-Item .github\workflows\JCOReflectorCLI8.0.runtimeconfig.json -Destination bin\net8.0\MASES.JCOReflectorCLI.runtimeconfig.json -Force
      
      - name: Remove Java files
        run: Remove-Item .\src\jvm\src\${{ matrix.framework }} -Recurse -Force
          
      - name: Reflect Java files
        run: .\bin\${{ matrix.framework }}\MASES.JCOReflectorCLI -JobType Reflect -JobFile .github\workflows\reflect_${{ matrix.framework }}.job

      - name: Compress source files
        run: Compress-Archive -Path .\src\jvm\src\${{ matrix.framework }}\* -DestinationPath .\source_${{ matrix.framework }}.zip

      - uses: actions/upload-artifact@v3
        with:
          name: LatestSource_${{ matrix.framework }}
          path: .\source_${{ matrix.framework }}.zip
          retention-days: 1

      - name: Build Java files
        run: .\bin\${{ matrix.framework }}\MASES.JCOReflectorCLI -JobType Build -JobFile .github\workflows\build_win19.job -JDKFolder %JAVA_HOME_11_X64%
        shell: cmd

      - name: Build JAR files .NET
        run: .\bin\${{ matrix.framework }}\MASES.JCOReflectorCLI -JobType CreateJars -JobFile .github\workflows\createjars_${{ matrix.framework }}_win19.job -JDKFolder %JAVA_HOME_11_X64%
        shell: cmd

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.framework }}
          path: .\bin\${{ matrix.framework }}\*.*
          retention-days: 1

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Prepare extra argument
        if: matrix.framework == 'net6.0'
        shell: bash
        run: echo "EXTRA_ARGUMENT=--CoreCLRApp:Microsoft.NET6.App" >> $GITHUB_ENV

      - name: Prepare extra argument
        if: matrix.framework == 'net7.0'
        shell: bash
        run: echo "EXTRA_ARGUMENT=--CoreCLRApp:Microsoft.NET7.App" >> $GITHUB_ENV

      - name: Build Java test source file
        run: javac -cp ./bin/${{ matrix.framework }}/JCOReflector.jar ./tests/jvm/java/src/hierarchy/*.java ./tests/jvm/java/src/mscorlib/*.java ./tests/jvm/java/src/nettest/*.java ./tests/jvm/java/src/refout/*.java

      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" mscorlib.HelloLock ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" mscorlib.HelloNET ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" mscorlib.HelloNETEvent ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" mscorlib.HelloIterator ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" hierarchy.HelloHierarchy ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" hierarchy.HelloInterfaces ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" nettest.HelloNETSocket ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" nettest.HelloNETSocket -async ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" refout.HelloRefOutBase ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: java -cp "./bin/${{ matrix.framework }}/JCOReflector.jar;./tests/jvm/java/src/" refout.HelloRefOut ${{ env.EXTRA_ARGUMENT }}
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}

      - name: Download Scala package
        run: C:\msys64\usr\bin\wget.exe https://downloads.lightbend.com/scala/2.13.5/scala-2.13.5.zip

      - name: Expand Scala package
        run: Expand-Archive -LiteralPath '.\scala-2.13.5.zip' -DestinationPath .\ -Force
        
      - name: Build Scala test source file
        shell: cmd
        run: |
          cd ./tests/jvm/scala
          mkdir output
          ..\..\..\scala-2.13.5\bin\scalac -toolcp "../../../bin/${{ matrix.framework }}/*" -d ./output ./src/main/scala/hierarchy/* ./src/main/scala/mscorlib/* ./src/main/scala/nettest/* ./src/main/scala/refout/*
              
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" mscorlib.HelloLock ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" mscorlib.HelloNet ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" mscorlib.HelloNETEvent ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" mscorlib.HelloIterator ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" hierarchy.HelloHierarchy ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" hierarchy.HelloInterfaces ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" nettest.HelloNETSocket ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" nettest.HelloNETSocket -async ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" refout.HelloRefOutBase ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: .\scala-2.13.5\bin\scala -toolcp "./bin/${{ matrix.framework }}/*;./tests/jvm/scala/output" refout.HelloRefOut ${{ env.EXTRA_ARGUMENT }}
        shell: cmd
        continue-on-error: true
        env:
          JCOBRIDGE_SCOPEDON: JCOReflector|1.0.0
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}
          
      - run: cd ./tests/jvm/scala && rmdir output /s /q
        shell: cmd
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: Errors_${{ matrix.framework }}
          path: .\hs_err_*
          retention-days: 1
